In [1]:
import os
import cv2
import numpy as np
import tensorflow as tf
import keras
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

# 載入數據集
data_path = 'preProcess/'
categories = [i + j for i in 'A23456789TJQK' for j in "shdc"]

images = []
labels = []

# 讀取圖片和標籤
for category in categories:
    path = os.path.join(data_path, category)
    class_num = categories.index(category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        img_array = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        images.append(img_array)
        labels.append(class_num)

print(img_array)
print(img_path)
# 將圖片轉換為NumPy數組
images = np.array(images)
labels = np.array(labels)

# 將標籤進行編碼
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

# 隨機打亂數據
images, labels = shuffle(images, labels, random_state=42)

# 切割數據集為訓練集和測試集
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# 正規化數據
X_train = X_train / 255.0
X_test = X_test / 255.0

# 建立卷積神經網絡模型
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(70, 70, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(len(categories), activation='softmax'))

# 編譯模型
opt = keras.optimizers.Adam()
model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


# 訓練模型
model.fit(X_train.reshape(-1, 70, 70, 1), y_train, epochs=40, validation_data=(X_test.reshape(-1, 70, 70, 1), y_test))


[[  0   2   0 ...   2   0   0]
 [  0   0   0 ...  15   4   2]
 [ 25  31  45 ...   1   5   4]
 ...
 [250 254 253 ...  53  10   0]
 [251 253 254 ...  28   0   2]
 [251 250 252 ...  22   0   1]]
preProcess/Kc\21-56-45_aug_9.jpg
Epoch 1/40


In [ ]:
import os
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

# 載入數據集
data_path = 'preProcess/'
categories = [i + j for i in 'A23456789TJQK' for j in "shdc"]

images = []
labels = []

# 讀取圖片和標籤
for category in categories:
    path = os.path.join(data_path, category)
    class_num = categories.index(category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        img_array = cv2.imread(img_path, cv2.IMREAD_COLOR)
        images.append(img_array)
        labels.append(class_num)

# 將圖片轉換為NumPy數組
images = np.array(images)
labels = np.array(labels)

# 將標籤進行編碼
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

# 隨機打亂數據
images, labels = shuffle(images, labels, random_state=42)

# 切割數據集為訓練集和測試集
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# 正規化數據
X_train = X_train / 255.0
X_test = X_test / 255.0

# 建立 ResNet50 模型
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(70, 70, 3))

# 增加自定義層
model = models.Sequential()
model.add(base_model)
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(len(categories), activation='softmax'))

# 凍結 ResNet50 的權重
base_model.trainable = False

# 編譯模型
model.compile(optimizer=optimizers.Adam(lr=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 訓練模型
model.fit(X_train.reshape(-1, 70, 70, 3), y_train, epochs=10, validation_data=(X_test.reshape(-1, 70, 70, 3), y_test))


In [25]:
x= X_train.reshape(-1, 70, 70, 1)

In [39]:
tmp = x[0]*255

In [40]:
newtemp = X_train[0]*255

: 

In [1]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
print(tf.__version__)

Num GPUs Available:  1
2.10.0


In [11]:
import os
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

# 載入數據集
data_path = 'preProcess/'
categories = [i + j for i in 'A23456789TJQK' for j in "shdc"]

images = []
labels = []

# 讀取圖片和標籤
for category in categories:
    path = os.path.join(data_path, category)
    class_num = categories.index(category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        img_array = cv2.imread(img_path, cv2.IMREAD_COLOR)
        images.append(img_array)
        labels.append(class_num)

# 將圖片轉換為NumPy數組
images = np.array(images)
labels = np.array(labels)

# 將標籤進行編碼
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

# 隨機打亂數據
images, labels = shuffle(images, labels, random_state=42)

# 切割數據集為訓練集和測試集
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# 正規化數據
X_train = X_train / 255.0
X_test = X_test / 255.0


In [12]:
import tensorflow as tf
from keras import *
# from tensorflow.keras import layers, models

def conv(x, filters, kernel_size=3, stride=1, activation='relu',pool=True):
    # Shortcut
    shortcut = x
    
    # First convolution
    x = layers.Conv2D(filters, kernel_size, strides=stride, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation(activation)(x)

    if pool:
        x = layers.MaxPooling2D(2,2)(x)
    

    # # Second convolution
    # x = layers.Conv2D(filters, kernel_size, strides=1, padding='same')(x)
    # x = layers.BatchNormalization()(x)
    
    # # Add shortcut to the output
    # x = layers.Add()([x, shortcut])
    # x = layers.Activation(activation)(x)
    
    return x

def resnet18(input_shape=(100, 100, 1), num_classes=13):
    input_tensor = layers.Input(shape=input_shape)
    
    # Initial Convolution
    x = conv(input_tensor,64,pool=False)
    x = conv(x,128,pool=False)
    res = conv(x,128,pool=False)
    res = conv(res,128,pool=False)
    x = layers.Add()([x,res])
    x = conv(x,256,pool = True)
    res = conv(x,256,pool=False)
    res = conv(res,256,pool=False)
    x = layers.Add()([x,res])
    x = conv(x,128,pool=True)
    x = conv(x,64,pool=True)

    # Global average pooling
    x = layers.Flatten()(x)
    x = layers.Dense(1024, activation='relu')(x)
    x = layers.Dense(512, activation='relu')(x)

    # Fully connected layer
    x = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inputs=input_tensor, outputs=x, name='resnet18')
    return model

# Build ResNet-18 model
resnet_model = resnet18(input_shape=(70, 70, 3), num_classes=52)

# Display model summary
resnet_model.summary()

resnet_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 訓練模型
resnet_model.fit(X_train.reshape(-1, 70, 70, 3), y_train, epochs=10, validation_data=(X_test.reshape(-1, 70, 70, 3), y_test))


Model: "resnet18"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 70, 70, 3)]  0           []                               
                                                                                                  
 conv2d_44 (Conv2D)             (None, 70, 70, 64)   1792        ['input_5[0][0]']                
                                                                                                  
 batch_normalization_36 (BatchN  (None, 70, 70, 64)  256         ['conv2d_44[0][0]']              
 ormalization)                                                                                    
                                                                                                  
 activation_36 (Activation)     (None, 70, 70, 64)   0           ['batch_normalization_36[0

KeyboardInterrupt: 