In [17]:
import os
import cv2
import numpy as np
import tensorflow as tf
import keras
from tensorflow.keras import layers, models,Input
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

# 載入數據集
data_path = 'preProcess/'
categories = [i + j for i in 'A23456789TJQK' for j in "shdc"]

images = []
labels = []

# 讀取圖片和標籤
for category in categories:
    path = os.path.join(data_path, category)
    class_num = categories.index(category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        img_array = cv2.imread(img_path)
        images.append(img_array)
        labels.append(class_num)

print(img_array)
print(img_path)
# 將圖片轉換為NumPy數組
images = np.array(images)
labels = np.array(labels)


# 隨機打亂數據
images, labels = shuffle(images, labels, random_state=42)

# 切割數據集為訓練集和測試集
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# 正規化數據
X_train = X_train / 255.0
X_test = X_test / 255.0

# 建立卷積神經網絡模型
model = models.Sequential()
model.add(Input(shape=(70, 70, 3)))
model.add(layers.Conv2D(32, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(len(categories), activation='softmax'))

# 編譯模型
opt = keras.optimizers.Adam()
model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


# 訓練模型
model.fit(X_train.reshape(-1, 70, 70, 3), y_train,epochs=50, validation_data=(X_test.reshape(-1, 70, 70, 3), y_test))


[[[  0   0   4]
  [200 204 209]
  [201 204 212]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[  0   0   4]
  [200 204 209]
  [201 204 212]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[  0   0   4]
  [200 204 209]
  [201 204 212]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[  0   0   0]
  [238 238 238]
  [237 237 237]
  ...
  [254 251 253]
  [254 251 253]
  [254 251 253]]

 [[  0   0   0]
  [238 238 238]
  [237 237 237]
  ...
  [254 251 253]
  [254 251 253]
  [254 251 253]]

 [[  0   0   0]
  [238 238 238]
  [237 237 237]
  ...
  [254 251 253]
  [254 251 253]
  [254 251 253]]]
preProcess/Kc\21-56-45_aug_3.jpg
Epoch 1/50
22/22 [==============================] - 3s 96ms/step - loss: 3.9864 - accuracy: 0.0262 - val_loss: 3.8824 - val_accuracy: 0.0756
Epoch 2/50
22/22 [==============================] - 2s 99ms/step - loss: 3.8171 - accuracy: 0.0451 - val_loss: 3.7339 - val_accuracy: 0.0814
Epoch 3/50
22/22 [==============================] - 2s 

KeyboardInterrupt: 

In [18]:
model.save("CNN.keras")